name: Development Continuous Deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create/Update Environment
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: docker build -t infra-builder .
      - name: Create or Update Environment
        run: docker run infra-builder /bin/bash ./scripts/setup_env_and_create_dev.sh $PASSPHRASE
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
