name: Development Continuous Deployment
on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    name: Create/Update Environment
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl unzip gnupg2 python3 python3-venv python3-setuptools jq

          mkdir /tmp/bin
          PATH="/tmp/bin:${PATH}"

          curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
          unzip /tmp/terraform.zip -d /tmp
          mv /tmp/terraform /tmp/bin

          curl -o gcp-script.sh https://sdk.cloud.google.com && chmod +x gcp-script.sh
          ./gcp-script.sh --install-dir=$(pwd) --disable-prompts

      - name: Setup Environment
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          ./scripts/decrypt.sh $PASSPHRASE

          gcloud auth activate-service-account --key-file=credentials.json
          gcloud config set compute/zone us-east1-b
          gcloud config set project vinnieapps

      - name: Create or Update Environment
        run: |
          sudo python3 setup.py install
          infrastructure create dev vinnieapps tf-state-dev-vinnieapps
